project_id = "vqlscgyjvattafvuxtks"

[functions.send-sms]
verify_jwt = false

[functions.sync-sms-delivery]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.generate-monthly-rents]
verify_jwt = false

[functions.monsms-balance]
verify_jwt = false

[functions.process-rent-reminders]
verify_jwt = false

[functions.send-sms-2fa-code]
verify_jwt = false

[functions.verify-sms-2fa-code]
verify_jwt = false