ALTER TABLE public.properties
ADD COLUMN IF NOT EXISTS acquisition_cost BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS notary_fees BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS acquisition_date DATE;